import { access, chmod, copyFile, cp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { resolve } from "node:path";
import { assertBuildEnvironment, telemetryBuildEnvironment } from "./telemetry-build.mjs";
import { pluginMarketplace } from "./plugin-marketplace.mjs";

const telemetryEnvironment = telemetryBuildEnvironment();
await assertBuildEnvironment("dist", telemetryEnvironment);
const manifestText = await readFile(".codex-plugin/plugin.json", "utf8");
const manifest = JSON.parse(manifestText);
const marketplace = resolve("release/marketplace");
const plugin = `${marketplace}/plugins/${manifest.name}`;
await access("dist/server.mjs");
await access("dist/app.html");
await access("dist/baguette/Baguette");
await access("dist/baguette/Baguette_Baguette.bundle");
await access("dist/agent-device-server.mjs");
await access("dist/ios-fps/mobile-dev-ios-fps");
for (const abi of ["arm64-v8a", "armeabi-v7a", "x86", "x86_64"]) await access(`dist/android-fps/${abi}/mobile-dev-fps`);
await access("dist/ios-mirror/darwin-arm64.node");
await access("dist/ios-mirror/third-party-licenses.txt");
await access("dist/ios-logs/mobile-dev-ios-logs");
await access("dist/ios-logs/third-party-licenses.txt");
for (const abi of ["arm64-v8a", "armeabi-v7a", "x86", "x86_64"]) await access(`dist/android-cpu/${abi}/mobile-dev-cpu`);
await access("dist/android-cpu/LICENSE");
await access("dist/serve-emu/src/cli.mjs");
await access("dist/serve-emu/vendor/scrcpy-server-v4.0");
await access("dist/agent-device/node_modules/agent-device/dist/apple/runner/AgentDeviceRunner/AgentDeviceRunner.xcodeproj/project.pbxproj");
await rm(plugin, { recursive: true, force: true });
await mkdir(plugin, { recursive: true });
for (const path of [".mcp.json", "README.md", "THIRD_PARTY_NOTICES.md"]) await copyFile(path, `${plugin}/${path}`);
for (const path of [".codex-plugin", "assets", "dist", "skills/mobile-dev", "skills/mobile-dev-setup"]) await cp(path, `${plugin}/${path}`, { recursive: true, verbatimSymlinks: true });
await mkdir(`${plugin}/docs`, { recursive: true });
await copyFile("docs/privacy-fork.md", `${plugin}/docs/privacy-fork.md`);
await mkdir(`${plugin}/scripts`, { recursive: true });
await copyFile("scripts/launch-mcp.sh", `${plugin}/scripts/launch-mcp.sh`);
await chmod(`${plugin}/scripts/launch-mcp.sh`, 0o755);
await chmod(`${plugin}/dist/baguette/Baguette`, 0o755);
await chmod(`${plugin}/dist/ios-logs/mobile-dev-ios-logs`, 0o755);
await mkdir(`${marketplace}/.agents/plugins`, { recursive: true });
const catalog = pluginMarketplace(manifest.name);
const catalogText = JSON.stringify(catalog, null, 2);
await writeFile(`${marketplace}/.agents/plugins/marketplace.json`, catalogText + "\n");
const archive = resolve(`release/${manifest.name}-${manifest.version}-darwin-arm64.zip`);
await rm(archive, { force: true });
const files = await readdir(plugin);
execFileSync("zip", ["-qr", archive, ...files], { cwd: plugin });
if ((await stat(archive)).size > 100_000_000) throw new Error("The plugin ZIP exceeds the 100 MB upload limit.");
console.log(`Plugin: ${plugin}\nMarketplace: ${marketplace}\nZIP: ${archive}`);
